# CopyLeft 2026 github.com/sepiol026-wq | telegram:@samsepi0l_ovf. Licensed under AGPLv3.
from typing import Any

def load_schema(schema_json: str) -> dict[str, Any]: ...
def schema_info() -> dict[str, Any]: ...
def serialize_method(method: str, args: str | dict[str, Any]) -> bytes: ...
def serialize_constructor(name: str, args: str | dict[str, Any]) -> bytes: ...
def deserialize_constructor(data: bytes) -> dict[str, Any] | list[Any]: ...
def dumps(obj: dict[str, Any] | bytes) -> bytes: ...
def loads(data: bytes) -> dict[str, Any] | list[Any]: ...
def aes_ige_enc(data: bytes, key: bytes, iv: bytes) -> bytes: ...
def aes_ige_dec(data: bytes, key: bytes, iv: bytes) -> bytes: ...
def aes_ige_enc_raw(data: bytes, key: bytes, iv: bytes) -> list[int]: ...
def aes_ige_dec_raw(data: bytes, key: bytes, iv: bytes) -> list[int]: ...
def aes_ige_fast_path() -> bool: ...
def aes_gcm_encrypt(key: bytes, nonce: bytes, plaintext: bytes, aad: bytes) -> bytes: ...
def aes_gcm_decrypt(key: bytes, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...
def cut(data: bytes, offset: int, length: int) -> bytes: ...
def pack(parts: list[bytes]) -> bytes: ...
