from typing import Any
from collections.abc import Sequence


def load_schema(schema_json: str) -> dict[str, int]: ...
def schema_info() -> dict[str, int]: ...
def serialize_method(method: str, args: dict[str, Any]) -> bytes: ...
def serialize_constructor(name: str, args: dict[str, Any]) -> bytes: ...
def deserialize_constructor(data: bytes) -> dict[str, Any] | list[object]: ...
def dumps(obj: bytes | dict[str, Any]) -> bytes: ...
def loads(data: bytes) -> dict[str, Any] | list[object]: ...
def aes_ige_enc(data: bytes, key: bytes, iv: bytes) -> bytes: ...
def aes_ige_fast_path() -> bool: ...
def aes_ige_dec(data: bytes, key: bytes, iv: bytes) -> bytes: ...
def aes_ige_enc_raw(data: bytes, key: bytes, iv: bytes) -> list[int]: ...
def aes_ige_dec_raw(data: bytes, key: bytes, iv: bytes) -> list[int]: ...
def aes_gcm_encrypt(key: bytes, nonce: bytes, plaintext: bytes, aad: bytes) -> bytes: ...
def aes_gcm_decrypt(key: bytes, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...
def cut(data: bytes, offset: int, length: int) -> bytes: ...
def pack(parts: Sequence[bytes]) -> bytes: ...
